dist: xenial
sudo: true
language: python
python:
  - "3.7"

install:
  - pip install -r requirements/production.txt -r requirements/local.txt

cache:
  - pip
  - apt

services:
  - postgresql
  - redis-server

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - build-essential
    - libpq-dev
    - gettext
    - zlib1g-dev


env:
  global:
  - PGPORT=5432
  - DATABASE_URL="postgres://testuser:testuser@127.0.0.1:5432/testdb"
  - REDIS_URL="redis://127.0.0.1:6379"
  - DJANGO_ADMIN_URL="admin/"
  - DJANGO_ALLOWED_HOSTS="127.0.0.1"
  - DJANGO_DEBUG="True"
  - DJANGO_SENTRY_ENVIRONMENT="test"
  - DJANGO_SETTINGS_MODULE="config.settings.test"
  - PYTHONHASHSEED="random"

before_script:
  - psql -c "CREATE USER testuser WITH PASSWORD 'testuser';" -U postgres
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO testuser;" -U postgres

script:
  - python manage.py check
  - python manage.py makemigrations --check
  - pytest
